# Generated by Django 3.2.5 on 2022-04-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=3)),
                ('student_age', models.CharField(max_length=3)),
            ],
        ),
    ]
